pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true
- task: CmdLine@2
  inputs:
    script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
      displayName: 'npm install and build'


- task: CmdLine@2
  inputs:
    script: 'npm run test-ci'
    displayName: 'npm run test-ci'
    

