pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.18.x'
- task: CmdLine@2
  displayName: build
  inputs:
    script: |
      npm install
      npm audit
      npm run build
- task: CmdLine@2
  displayName: test
  inputs:
    script: 'npm run test-ci'
    failOnStderr: true
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'diegofelipeorozco'
    scannerMode: 'CLI'
    configMode: 'file'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS S3'
    regionName: 'us-east-1'
    bucketName: 'artefactospreproduccion'
    globExpressions: '*.zip'
    targetFolder: 'pet-book'
    createBucket: true